# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserActivateCertificate',
            new_name='CertificateActive',
        ),
        migrations.RenameModel(
            old_name='UserCertificate',
            new_name='CertificateAssign',
        ),
        migrations.RenameModel(
            old_name='CertificateDuration',
            new_name='CertificateInfo',
        ),
    ]
